### ISSUE TITLE
php7.3,安装后,配置nginx后,报错.

### ISSUE THREAD

**Issue by feng99** [laynefyc/php-monitor#6]
第一个问题
扩展名字 最新的叫 tideways_xhprof.so 
我修改了config.php
```
    //'extension' => 'tideways',
    'extension' => 'tideways_xhprof',
```
然后提示
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function 
Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in 
/data/web/easyphalcon/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php on line 2476 and exactly 2 expected in 
/data/web/easyphalcon/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php:2467 Stack trace: #0 /data/web/easyphalcon/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php(2476): Illuminate\Database\Eloquent\Model->setAttribute(Object(Carbon\Carbon)) #1 
/data/web/easyphalcon/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php(2912): Illuminate\Database\Eloquent\Model->setAttribute('', Object(Carbon\Carbon)) #2 
/data/web/easyphalcon/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php(1643): Illuminate\Database\Eloquent\Model->__set('', Object(Carbon\Carbon)) #3 /data/web/easyphalcon/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php(1615): Illum in /data/web/easyphalcon/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php on line 2467
```

**Comment by feng99** [comment]
tideways_xhprof的版本是

Version => 5.0.2

**Comment by feng99** [comment]
PHP 7.3.11

**Comment by feng99** [comment]
作者您好  请回复下 谢谢   正打算使用此工具.

**Comment by laynefyc** [comment]
Try install tideways v4.1.7
