### ISSUE TITLE
在phalcon3.4.5 php7.3下使用报错

### ISSUE THREAD

**Issue by feng99** [laynefyc/php-monitor#8]
使用方式为:

```
//加载php-monitor监控系统 
require '/data/softdata/php-monitor/src/autoPrepend.php';

// 加载composer
require ROOT_PATH . '/composer/vendor/autoload.php';
```

访问项目: 
```
<br />
<b>Notice</b>:  Trying to get property 'application' of non-object in <b>/data/web/github/phalcondemo/app/bootstrap/services.php</b> on line <b>47</b><br />
<br />
<b>Notice</b>:  Trying to get property 'viewsDir' of non-object in <b>/data/web/github/phalcondemo/app/bootstrap/services.php</b> on line <b>47</b><br />
<br />
<b>Fatal error</b>:  Uncaught Phalcon\Mvc\View\Exception: Views directory must be a string or an array in phalcon/mvc/view.zep:179
Stack trace:
#0 /data/web/github/phalcondemo/app/bootstrap/services.php(47): Phalcon\Mvc\View-&gt;setViewsDir(NULL)
#1 [internal function]: Closure-&gt;{closure}()
#2 [internal function]: Phalcon\Di\Service-&gt;resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#3 [internal function]: Phalcon\Di-&gt;get('view', NULL)
#4 /data/web/github/phalcondemo/app/Sdks/Library/Helpers/DiHelper.php(24): Phalcon\Di-&gt;getShared('view')
#5 /data/web/github/phalcondemo/app/Sdks/Core/System/Flash/CustomFlash.php(51): App\Sdks\Library\Helpers\DiHelper::getShared('view')
#6 /data/web/github/phalcondemo/app/Sdks/Core/System/Flash/CustomFlash.php(85): App\Sdks\Core\System\Flash\CustomFlash-&gt;outputJson(Object(stdClass), -1, '\nError Code: 50...')
#7 /data/web/github/phalcondemo/app/bootstrap/exception_handler.php(58): App\Sdks\Core\System\Flash\CustomFlash-&gt;errorJson(Array, -1, '\nError Code: 50...')
#8 [internal function]: {closure}(Obje in <b>phalcon/mvc/view.zep</b> on line <b>179</b><br />
<br />
<b>Fatal error</b>:  Uncaught ArgumentCountError: Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in /data/web/github/phalcondemo/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php on line 2476 and exactly 2 expected in /data/web/github/phalcondemo/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php:2467
Stack trace:
#0 /data/web/github/phalcondemo/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php(2476): Illuminate\Database\Eloquent\Model-&gt;setAttribute(Object(Carbon\Carbon))
#1 /data/web/github/phalcondemo/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php(2912): Illuminate\Database\Eloquent\Model-&gt;setAttribute('', Object(Carbon\Carbon))
#2 /data/web/github/phalcondemo/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php(1643): Illuminate\Database\Eloquent\Model-&gt;__set('', Object(Carbon\Carbon))
#3 /data/web/github/phalcondemo/composer/vendor/illuminate/database/Illuminat in <b>/data/web/github/phalcondemo/composer/vendor/illuminate/database/Illuminate/Database/Eloquent/Model.php</b> on line <b>2467</b><br />
```

**Comment by lz71** [comment]
php 7.3 扩展：tideways_xhprof 5.0.2
访问项目：接口没有返回任何东西
Class 'vFactory' not found  
                              


Fatal error: Uncaught ArgumentCountError: Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in D:\phpstudy
_pro\WWW\service\wdd_live\addons\shimmer_liveshop\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php on line 519
and exactly 2 expected in D:\phpstudy_pro\WWW\service\wdd_live\addons\shimmer_liveshop\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Co
ncerns\HasAttributes.php:511
Stack trace:
#0 D:\phpstudy_pro\WWW\service\wdd_live\addons\shimmer_liveshop\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.ph
p(519): Illuminate\Database\Eloquent\Model->setAttribute(Object(Carbon\Carbon))
#1 D:\phpstudy_pro\WWW\service\wdd_live\addons\shimmer_liveshop\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1291): Illumina
te\Database\Eloquent\Model->setAttribute('', Object(Carbon\Carbon))
#2 D:\phpstudy_pro\WWW\service\wdd_live\addons\shimmer_liveshop\vendor\laravel\framework\src\Illuminate\Database in D:\phpstudy_pro\WWW\service\wdd
_live\addons\shimmer_liveshop\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php on line 511

**Comment by lz71** [comment]
@feng99 大佬的问题解决了吗

**Comment by feng99** [comment]
> @feng99 大佬的问题解决了吗

没有  我放弃使用这个了   修改为使用  Tideways+xhgui
效果也完全符合要求  你可以看看   网络上的教程比较多.

**Comment by laynefyc** [comment]
Try install tideways v4.1.7
